FROM python:3.12-slim

WORKDIR /app

COPY requirements-dev.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .
ENV PYTHONPATH=/app

CMD ["uvicorn", "app.handler_http:app", "--host", "0.0.0.0", "--port", "8000"]
