services:
  fastapi-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8001"
    profiles: ["fastapi-service"]

  fastapi-lambda:
    build:
      context: .
      dockerfile: Dockerfile.lambda
    ports:
      - "9000:8002"
    profiles: ["fastapi-lambda"]
