name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    # Removed branches: - main to allow all pull requests to main
    # Validation will be filtered by the job condition

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref != 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for commit validation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements-ci.txt

      - name: Validate conventional commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: pytest tests/unit/ -v --cov=app --cov-report=term

      - name: Run integration tests
        run: pytest tests/integration/ -v --cov=app --cov-report=term --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for semantic release

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements-ci.txt

      - name: Run unit tests
        run: pytest tests/unit/ -v --cov=app --cov-report=term

      - name: Run integration tests
        run: pytest tests/integration/ -v --cov=app --cov-report=term --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7

      - name: Semantic Release
        run: semantic-release publish --github-token ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from semantic release
        id: get-version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if image exists
        id: check-image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}/friar-tuck-service-example:${{ steps.get-version.outputs.VERSION }}
          if docker manifest inspect $IMAGE_TAG > /dev/null 2>&1; then
            echo "Image exists, skipping push"
            echo "skip_push=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist, proceeding with push"
            echo "skip_push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.check-image.outputs.skip_push == 'false'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/friar-tuck-service-example:${{ steps.get-version.outputs.VERSION }} .
          docker push ghcr.io/${{ github.repository }}/friar-tuck-service-example:${{ steps.get-version.outputs.VERSION }}
