name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for Git tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest tests/unit/ -v --cov=app --cov-report=term

      - name: Run integration tests
        run: pytest tests/integration/ -v --cov=app --cov-report=term --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 14

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for Git tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine and create new version tag
        id: tag-version
        run: |
          # Get the latest tag or use fallback
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Extract version parts (e.g., v0.0.0 -> 0.0.0)
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG#v}"
          # Check if the commit is already tagged
          if git tag --contains HEAD | grep -q .; then
            # Use the latest tag containing the commit
            TAG=$(git tag --contains HEAD | sort -V | tail -n 1)
            echo "Commit is already tagged, using existing tag: $TAG"
            VERSION=$TAG
          else
            # Increment patch version for untagged commit
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"
            # Validate version is not lower than latest tag
            if [ "$(printf '%s\n' "$NEW_VERSION" "$LATEST_TAG" | sort -V | head -n 1)" != "$LATEST_TAG" ]; then
              echo "Error: Calculated version $NEW_VERSION is lower than latest tag $LATEST_TAG"
              exit 1
            fi
            echo "Creating new tag: $NEW_VERSION"
            git tag $NEW_VERSION
            git push origin $NEW_VERSION
            VERSION=$NEW_VERSION
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if image exists
        id: check-image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}/friar-tuck-service-example:${{ steps.tag-version.outputs.VERSION }}
          if docker manifest inspect $IMAGE_TAG > /dev/null 2>&1; then
            echo "Image exists, skipping push"
            echo "skip_push=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist, proceeding with push"
            echo "skip_push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.check-image.outputs.skip_push == 'false'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/friar-tuck-service-example:${{ steps.tag-version.outputs.VERSION }} .
          docker push ghcr.io/${{ github.repository }}/friar-tuck-service-example:${{ steps.tag-version.outputs.VERSION }}
